### ISSUE TITLE
问一下这个train数据集为什么不用单一的背景呢

### ISSUE THREAD

**Issue by andeyeluguo** [RPC-Dataset/RPC-Dataset.github.io#1]
首先感谢开源这个数据集，但是在复现的时候发现需要显著性检测和随机条件场等理论把图像的mask扣出来，感觉太麻烦，如果是单一背景（比如全黑全白），就比较容易抠出来，不知道当时设计的时候是怎么打算的？

**Comment by DIYer22** [comment]
Train set 上, 背景本来就是比较纯净和一致的颜色和纹理, 你可以直接试一下你想尝试的方法.

**Comment by ShihuaiXu** [comment]
@andeyeluguo 
哥 想问一下你拿到syn和render的数据了嘛 能否分享一下您的方法
