### ISSUE TITLE
数据解压之后train2019只有1万张图片

### ISSUE THREAD

**Issue by happywmzzz** [RPC-Dataset/RPC-Dataset.github.io#2]
数据是从百度云里面下载的，cat z01 z02 z03 zip > full.zip 之后unzip ，train2019里面只有39个类，1万张，不全呀，应该是200类5万张吧，是我下载的问题吗

**Comment by DIYer22** [comment]
我不清楚 Linux 下如何 unzip 这么多 zip文件, 搜索了一下, 你的方法应该不对, 你试一下这个:

https://askubuntu.com/questions/31298/how-to-extract-and-join-files-xxx-zip-xxx-z01-and-xxx-z02/161157
