### ISSUE TITLE
About the Syn and Render data

### ISSUE THREAD

**Issue by gaoyuchris** [RPC-Dataset/RPC-Dataset.github.io#3]
I wonder if you can provide the syn and render data? thanks.

**Comment by DIYer22** [comment]
I am sorry, the syn and render datas are too big(more than 160Gb) to release.

**Comment by ShihuaiXu** [comment]
any hope to release it? 160Gb is ok for me. thank you in advance.

**Comment by DIYer22** [comment]
@ShihuaiXu Sorry, I can't download from our internal network cause security.

**Comment by ShihuaiXu** [comment]
> @ShihuaiXu Sorry, I can't download from our internal network cause security.

thank you very much

**Comment by ShihuaiXu** [comment]
@gaoyuchris 
Sir, have you get the syn and render data? would like to show the detail of your method? I am interested in it, especially how to get the syn and render images
