### ISSUE TITLE
 baseline 的源代码

### ISSUE THREAD

**Issue by lufficc** [RPC-Dataset/RPC-Dataset.github.io#4]
复现论文里的 baseline 有很大的随机性（和随机生成合成图像的策略有较大关系），而且论文里用到的 Detecting salient objects via color and texture compactness hypotheses 方法也没有开源实现，因此希望能公开 baseline 的源代码，非常感谢。

**Comment by ShihuaiXu** [comment]
兄弟 请问你解决这个问题了嘛
