### ISSUE TITLE
数据集处理

### ISSUE THREAD

**Issue by ldhai** [RPC-Dataset/RPC-Dataset.github.io#5]
请问可以公布一下数据集预处理部分的代码吗？

**Comment by ruisv** [comment]
我也想知道如何进行训练数据处理 我在提取其中图片时并不准确

**Comment by DIYer22** [comment]
我不清楚此处的"预处理"是指数据增强还是指数据集本身? 

如果是数据集本身, 发布的 RPC 数据集和 COCO detection 的数据格式一模一样, 可以参考 COCO 的数据是如何处理的 比如下文的 "Object Instance 类型的标注格式" 章节:
https://zhuanlan.zhihu.com/p/29393415

**Comment by ruisv** [comment]
@DIYer22 
您好，我的问题是在处理训练集时 从图像中分离出物体

**Comment by ruisv** [comment]
@DIYer22 
就是在您Paper  Figure 10. Pipeline of our proposed method for the ACO task.
中的第一步
1. Segmenting product from exemplar images
我无法从您的训练集中提取相应的细节
我对Saliency detection 了解有限
因此想请教您是否有此数据集对应的提取训练集中细节的方法。

**Comment by ruisv** [comment]
因此想向您请教 Segmenting product from exemplar images 这一步是如何进行实现的
给您添麻烦了， 谢谢您！ 
@DIYer22

**Comment by ShihuaiXu** [comment]
> 因此想向您请教 Segmenting product from exemplar images 这一步是如何进行实现的
> 给您添麻烦了， 谢谢您！
> @DIYer22

兄弟，请问这个问题你解决了嘛
