### ISSUE TITLE
Resolution of training dataset

### ISSUE THREAD

**Issue by Monica2511** [RPC-Dataset/RPC-Dataset.github.io#6]
I want to know the resolution of training dataset. I see the resolution of data is 2592x1944, but did you resize the images when put in MaskRcnn Model ?

**Comment by DIYer22** [comment]
We follow this [config](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/config/defaults.py#L42) which is write by maskrcnn-benchmark

**Comment by ShihuaiXu** [comment]
@DIYer22 
Sir, have you use the  saliency detection method and CRF to get the syn and render data? Would mind share the code to me?

**Comment by DIYer22** [comment]
@ShihuaiXu Here is code for saliency detection, but it's out of maintain. https://github.com/DIYer22/salience-ELM

**Comment by ShihuaiXu** [comment]
thank you very much, Sir.





------------------ Original ------------------

**Comment by ShihuaiXu** [comment]
> @ShihuaiXu Here is code for saliency detection, but it's out of maintain. https://github.com/DIYer22/salience-ELM

Would you mind tell me which version in https://github.com/DIYer22/salience-ELM you used? the old version in 2016 基于ELM的图像显著区域检测
or the new version in 2018? 增加了 Detecting Salient Objects via Color and Texture Compactness Hypotheses 的原始 Saliency 方法

**Comment by DIYer22** [comment]
@ShihuaiXu new one.

**Comment by ShihuaiXu** [comment]
> @ShihuaiXu new one.

Thank you very much, your environment is python2.7 or python3? which one?

**Comment by DIYer22** [comment]
I forget, you can try py3 first.

**Comment by ShihuaiXu** [comment]
> I forget, you can try py3 first.

Thanks for your kindly help.
