### ISSUE TITLE
Setting up for training CycleGAN

### ISSUE THREAD

**Issue by edwardnguyen1705** [RPC-Dataset/RPC-Dataset.github.io#9]
Dear @DIYer22 ,
Thanks for sharing your work.
I have followed your method and successfully synthesized images. Now, it comes to the part of training the [CycleGAN](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix), although after reading the "D. Details of checkout images synthesis and checkout image generation via domain translation" part, I still do have have any clue how to select datasets for training the [CycleGAN](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix). Here is my settings:

- synthesized image' size: 1816
- divide the synthesized images into two sets: trainA, testA
- trainB: RPC/test2019, testB: RPC/val2019

Here is training commands:
```
DATA_ROOT=/home/thanhnv/Datasets/RPC_cycleGAN
python train.py --dataroot ${DATA_ROOT} \
                --name rpc_syn2real \
                --model cycle_gan \
                --n_epochs 200 \
                --gpu_ids 5 \
                --batch_size 1 \
                --preprocess scale_width_and_crop \
                --load_size 1816 \
                --crop_size 256
```

I observed that the number of objects in the generated/fake images (bottom) are different from the real ones (synthesised, top).

![epoch036_real_A](https://user-images.githubusercontent.com/7928673/88470826-a1019400-cf2b-11ea-86a1-6b89a88df2ff.png)
![epoch036_fake_B](https://user-images.githubusercontent.com/7928673/88470827-a6f77500-cf2b-11ea-8a32-03b359a9b51b.png)

Could you please give me some suggestions on how to train the [CycleGAN](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix) properly.

I really appreciate your time.

**Comment by DIYer22** [comment]
When testing, a full-size image is required(in your case, should be 1816).

What's your input image size when testing?

**Comment by ShihuaiXu** [comment]
@edwardnguyen1705 
would like to share you code of generating synthesized images? Thank you very much!

**Comment by DIYer22** [comment]
@ShihuaiXu   Sorry, I can't share this code cause security.

**Comment by ShihuaiXu** [comment]
> @ShihuaiXu Sorry, I can't share this code cause security.

okay, I understand, thank you very much
